// UE3/bookshop-react/src/components/home.js
import { Link } from "react-router-dom";

export default function Home(){
    return (
        <div className="ui container">
            <h1>Home</h1>
            <p>Willkommen im WEA5 BookShop</p>
            <Link className="ui red button" to="/books">
                Buchliste ansehen
                <i className="right arrow icon"/>
            </Link>
        </div>
    );
}

// UE1/Bookshop/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'wea5-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="ui container">
    <h1>Home</h1>
    <p>Willkommen im WEA5 Bookshop.</p>
    <a routerLink="../books" class="ui red button">
        Buchliste ansehen <i class="right arrow icon"></i>
    </a>
</div>
