// UE2/BookShop-Template/src/app/book-list-item/book-list-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { environment } from 'src/environments/environment';
import { Book } from '../shared/book';

@Component({
  selector: 'a.wea5-book-list-item',
  templateUrl: './book-list-item.component.html',
  styles: [
  ]
})
export class BookListItemComponent implements OnInit {

  @Input() book: Book = new Book();

  constructor(private sanitizer: DomSanitizer) { }

  ngOnInit(): void {
  }

  imageUrl() {
    return this.sanitizer.bypassSecurityTrustResourceUrl(`${environment.images}/${this.book.picture}`)
  }

}

<img class="ui tiny image" *ngIf="book.picture" [src]="imageUrl()">
<div class="content">
  <div class="header">{{ book.title }}</div>
  <div class="description"> {{ book.author }} </div>
  <div class="extra">Year {{ book.year }}</div>
</div>

// UE3/bookshop-react/src/components/book-list-item.js
import { Fragment } from "react";
import { baseUrl } from "./book-api";

export default function BookListItem(props) {
    return (
        <Fragment>
            <img className="ui tiny image" src={`${baseUrl}/${props.book.picture}`} alt="book cover" />
            <div className='content'>
                <div className='header'>{props.book.title}</div>
                <div className='description'>{props.book.author}</div>
                <div className='extra'>Year: {props.book.year}</div>
            </div>
        </Fragment>
    );
}
